"use client";

import { useMemo, useState, useEffect } from "react";
import workbook from "@/data/workbook.json";
import library from "@/data/library-context.json";

type Row = (string | number | null)[];
const planRows = workbook.Plan.slice(1) as Row[];
const mockRows = workbook.Mocks.slice(1) as Row[];
const roadmapRows = workbook.Roadmaps.slice(1) as Row[];
const compRows = workbook.CompReality.slice(1) as Row[];
const tracks = Array.from(new Set(planRows.map((r) => String(r[0]))));
const months = Array.from(new Set(planRows.map((r) => Number(r[1])))).sort((a, b) => a - b);
const pct = (done: number, total: number) => total ? Math.round((done / total) * 100) : 0;
const topicKey = (r: Row) => `${String(r[0])}::${String(r[2])}`;

function Link({ href, children }: { href: string; children: React.ReactNode }) { return <a className="resource-link" href={href} target="_blank" rel="noreferrer">{children}<span>↗</span></a>; }
function Metric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: string }) { return <div className={`metric ${tone}`}><span className="metric-label">{label}</span><strong>{value}</strong><span className="metric-detail">{detail}</span></div>; }

export default function Home() {
  const [tab, setTab] = useState("Overview");
  const [track, setTrack] = useState("All tracks");
  const [month, setMonth] = useState("All months");
  const [query, setQuery] = useState("");
  const [statuses, setStatuses] = useState<Record<string, string>>({});
  const [askOpen, setAskOpen] = useState(false);
  const [askText, setAskText] = useState("");
  const [messages, setMessages] = useState<{ role: "user" | "assistant"; content: string }[]>([]);
  const [asking, setAsking] = useState(false);
  useEffect(() => { try { setStatuses(JSON.parse(localStorage.getItem("lumen-statuses") || "{}")); } catch {} }, []);
  const setStatus = (r: Row, status: string) => { const next = { ...statuses, [topicKey(r)]: status }; setStatuses(next); localStorage.setItem("lumen-statuses", JSON.stringify(next)); };
  const filtered = useMemo(() => planRows.filter((r) => (track === "All tracks" || r[0] === track) && (month === "All months" || String(r[1]) === month) && String(r[2]).toLowerCase().includes(query.toLowerCase())), [track, month, query]);
  const done = planRows.filter((r) => (statuses[topicKey(r)] || r[15]) === "Done").length;
  const skipped = planRows.filter((r) => r[15] === "Skipped").length;
  const hours = planRows.reduce((n, r) => n + Number(r[13] || 0), 0);
  const doneHours = planRows.filter((r) => (statuses[topicKey(r)] || r[15]) === "Done").reduce((n, r) => n + Number(r[13] || 0), 0);
  const monthHours = months.map((m) => ({ month: m, hours: planRows.filter((r) => Number(r[1]) === m).reduce((n, r) => n + Number(r[13] || 0), 0) }));
  const maxMonthHours = Math.max(...monthHours.map((x) => x.hours));
  const setView = (name: string) => { setTab(name); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const askLumen = async (prompt = askText) => {
    if (!prompt.trim() || asking) return;
    const context = filtered.slice(0, 8).map((r) => `${r[0]} | ${r[2]} | ${r[3]} | resources: ${r[4]}, ${r[7]}, ${r[10]}`).join("\n");
    setMessages((m) => [...m, { role: "user", content: prompt }]); setAskText(""); setAsking(true);
    try { const res = await fetch("/api/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, context, history: messages }) }); const data = await res.json(); setMessages((m) => [...m, { role: "assistant", content: data.answer || data.error || "Lumen could not answer right now." }]); } catch { setMessages((m) => [...m, { role: "assistant", content: "Lumen is unavailable. Add MINIMAX_API_KEY in Vercel project settings and try again." }]); } finally { setAsking(false); }
  };

  return <main className="shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">LU</div><div><div className="brand-name">Lumen</div><div className="brand-sub">Rasul · 9-month operating view</div></div></div><div className="top-actions"><span className="sync-dot" /> Workbook snapshot · Sep 2026 <button className="ask-trigger" onClick={() => setAskOpen(true)}>✦ Ask Lumen</button><button className="ghost-button">↗ Share</button></div></header>
    <section className="hero"><div><p className="kicker">Preparation command center</p><h1>Build proof, not just knowledge.</h1><p className="hero-copy">Your 612-hour Senior FDE plan, reduced to the pace, practice, and proof that matter this week.</p></div><div className="hero-note"><span className="note-pin">●</span><div><strong>Current focus</strong><p>Month 1 · foundations and production fluency</p></div></div></section>
    <nav className="tabs" aria-label="Workbook views">{["Overview", "Plan", "Mocks", "Roadmaps", "Library", "Comp reality"].map((item) => <button key={item} className={tab === item ? "tab active" : "tab"} onClick={() => setView(item)}>{item}</button>)}</nav>
    {tab === "Overview" && <>
      <section className="metric-grid"><Metric label="Plan progress" value={`${pct(done, planRows.length - skipped)}%`} detail={`${done} of ${planRows.length - skipped} non-skipped topics`} tone="rose" /><Metric label="Hours remaining" value={`${Math.max(hours - doneHours, 0)}`} detail={`of ${hours} planned hours`} tone="teal" /><Metric label="Weekly commitment" value="16h" detail="38.3 weeks at this pace" tone="brass" /><Metric label="Mocks" value={`${mockRows.reduce((n, r) => n + Number(r[6] || 0), 0)} / ${mockRows.reduce((n, r) => n + Number(r[1] || 0), 0)}`} detail="completed / target" tone="ink" /></section>
      <section className="content-grid"><div className="panel wide"><div className="panel-head"><div><p className="eyebrow">Pace map</p><h2>Where the hours go</h2></div><span className="panel-meta">612h · 12 tracks</span></div><div className="bar-chart">{monthHours.map((item) => <div className="bar-item" key={item.month}><div className="bar-value">{item.hours}h</div><div className="bar-track"><div className="bar-fill" style={{ height: `${Math.max(12, item.hours / maxMonthHours * 100)}%` }} /></div><div className="bar-label">M{item.month}</div></div>)}</div><div className="chart-foot"><span><i className="legend-dot rose" /> planned hours</span><span>Peak: Month 2 · 79h</span></div></div><div className="panel"><div className="panel-head"><div><p className="eyebrow">Next action</p><h2>Start here</h2></div><span className="priority">P1</span></div><div className="next-action"><div className="action-index">01</div><div><h3>{String(planRows[0][2])}</h3><p>{String(planRows[0][3]).slice(0, 118)}…</p><Link href={String(planRows[0][5])}>Open reading</Link></div></div><button className="primary-button" onClick={() => setView("Plan")}>Open the plan <span>→</span></button></div></section>
      <section className="content-grid lower"><div className="panel wide"><div className="panel-head"><div><p className="eyebrow">By track</p><h2>Coverage at a glance</h2></div><button className="text-button" onClick={() => setView("Plan")}>View all →</button></div><div className="track-list">{tracks.map((name) => { const rows = planRows.filter((r) => r[0] === name); const h = rows.reduce((n, r) => n + Number(r[13] || 0), 0); return <button className="track-row" key={name} onClick={() => { setTrack(name); setView("Plan"); }}><span className="track-name">{name}</span><span className="track-count">{rows.length} topics</span><span className="track-progress"><span style={{ width: `${pct(rows.filter((r) => (statuses[topicKey(r)] || r[15]) === "Done").length, rows.length)}%` }} /></span><span className="track-hours">{h}h</span></button>; })}</div></div><div className="panel reality"><p className="eyebrow">Reality check</p><h2>Target calibration</h2><p>“$250K” is a 2–3 year target from Pune, not a 9-month promise. The nearer proof point is a strong global-remote India role.</p><button className="text-button" onClick={() => setView("Comp reality")}>Read the assumptions →</button></div></section>
    </>}
    {tab === "Plan" && <section className="panel full-panel"><div className="panel-head plan-head"><div><p className="eyebrow">81 topics · three resources each</p><h2>Plan explorer</h2></div><div className="filters"><input aria-label="Search topics" placeholder="Search topics…" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={track} onChange={(e) => setTrack(e.target.value)}><option>All tracks</option>{tracks.map((t) => <option key={t}>{t}</option>)}</select><select value={month} onChange={(e) => setMonth(e.target.value)}><option>All months</option>{months.map((m) => <option key={m}>{m}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>Topic</th><th>Track</th><th>Month</th><th>Hours</th><th>Depth target</th><th>Resources</th><th>Progress</th></tr></thead><tbody>{filtered.map((r, i) => <tr key={`${r[0]}-${r[2]}-${i}`}><td><strong>{String(r[2])}</strong><span className="status">{statuses[topicKey(r)] || r[15] || "Not started"}</span></td><td>{String(r[0]).replace(/^[A-Z]\. /, "")}</td><td>M{String(r[1])}</td><td>{String(r[13])}h</td><td className="depth">{String(r[3])}</td><td className="resource-stack"><Link href={String(r[5])}>Read</Link><Link href={String(r[8])}>Watch</Link><Link href={String(r[11])}>Do</Link></td><td><select className="status-select" aria-label={`Update ${String(r[2])}`} value={statuses[topicKey(r)] || String(r[15] || "Not started")} onChange={(e) => setStatus(r, e.target.value)}><option>Not started</option><option>In progress</option><option>Done</option><option>Skipped</option></select><button className="ask-row" onClick={() => { setAskOpen(true); setAskText(`Explain ${String(r[2])} with a practical example and a 20-minute exercise.`); }}>Ask</button></td></tr>)}</tbody></table></div></section>}
    {tab === "Mocks" && <section className="panel full-panel"><div className="panel-head"><div><p className="eyebrow">Interview proof</p><h2>Mocks & repetitions</h2></div><span className="panel-meta">{mockRows.length} practice loops</span></div><div className="mock-grid">{mockRows.map((r, i) => <div className="mock-row" key={i}><div className="mock-title"><strong>{String(r[0])}</strong><span>M{String(r[3])}</span></div><div className="mock-bar"><span style={{ width: `${pct(Number(r[6] || 0), Number(r[1] || 0))}%` }} /></div><div className="mock-stats"><b>{String(r[6] || 0)} / {String(r[1])}</b><span>{String(r[5])}</span></div></div>)}</div></section>}
    {tab === "Roadmaps" && <section className="panel full-panel"><div className="panel-head"><div><p className="eyebrow">External scaffolding</p><h2>Roadmaps & guides</h2></div></div><div className="resource-grid">{roadmapRows.map((r, i) => <a className="resource-card" href={String(r[1])} target="_blank" rel="noreferrer" key={i}><span className="resource-number">{String(i + 1).padStart(2, "0")}</span><div><h3>{String(r[0])}</h3><p>{String(r[2])}</p></div><span className="arrow">↗</span></a>)}</div></section>}
    {tab === "Library" && <section className="panel full-panel"><div className="panel-head"><div><p className="eyebrow">Private study context</p><h2>{library.length} books, one learning spine</h2></div><span className="panel-meta">{library.reduce((n, b) => n + b.pages, 0).toLocaleString()} pages indexed</span></div><p className="library-note">Lumen uses the book map to connect ideas across levels, from first principles to production systems, without placing the source PDFs in the public deployment.</p><div className="book-list">{library.map((book, i) => <article className="book-row" key={book.id}><div className="book-number">{String(i + 1).padStart(2, "0")}</div><div><h3>{book.title}</h3><p>{book.author} · {book.pages} pages · {book.role}</p><div className="topic-chips">{book.topics.map((topic) => <span key={topic}>{topic}</span>)}</div></div><button className="ask-row" onClick={() => { setAskOpen(true); setAskText(`Build a practical study sequence connecting ${book.title} to my Senior FDE plan.`); }}>Ask Lumen</button></article>)}</div></section>}
    {tab === "Comp reality" && <section className="panel full-panel"><div className="panel-head"><div><p className="eyebrow">Context, not promises</p><h2>Compensation reality</h2></div></div><div className="comp-list">{compRows.map((r, i) => <article className="comp-row" key={i}><div><span className="comp-market">{String(r[0])}</span><h3>{String(r[1])}</h3></div><p>{String(r[3])}</p><span className={`prob prob-${i}`}>{String(r[4])}</span></article>)}</div></section>}
    {askOpen && <aside className="ask-panel" aria-label="Ask Lumen"><div className="ask-head"><div><p className="eyebrow">Lumen study guide</p><h2>Ask Lumen</h2></div><button className="close-button" onClick={() => setAskOpen(false)}>×</button></div><p className="ask-intro">Ask for a plain-English explanation, a session recap, or the next hands-on step. Lumen sees the filtered plan and the indexed study library.</p><div className="context-status"><span className="sync-dot" /> Plan snapshot + 16-book index</div><div className="suggestions"><button onClick={() => askLumen("Explain the current topic like I am preparing for a senior FDE interview.")}>Explain this</button><button onClick={() => askLumen("Turn the current topic into a 20-minute hands-on exercise.")}>Give me a lab</button><button onClick={() => askLumen("What should I be able to say or build after this session?")}>Check grasp</button></div><div className="messages">{messages.length === 0 && <div className="empty-chat">Try asking Lumen to explain the topic you are watching right now.</div>}{messages.map((m, i) => <div className={`message ${m.role}`} key={i}><span>{m.role === "user" ? "You" : "Lumen"}</span><p>{m.content}</p></div>)}{asking && <div className="message assistant"><span>Lumen</span><p>Working through the plan context…</p></div>}</div><form className="ask-form" onSubmit={(e) => { e.preventDefault(); askLumen(); }}><input value={askText} onChange={(e) => setAskText(e.target.value)} placeholder="Ask about what you are learning…" /><button aria-label="Send question" disabled={asking || !askText.trim()}>→</button></form><div className="ask-foot">MiniMax M3 · key stays server-side</div></aside>}
    <footer><span>Built from Rasul&apos;s Senior FDE Plan.xlsx</span><span>Five workbook views · one operating system</span></footer>
  </main>;
}
