/**
 * Diagnosing an install you will never have access to.
 *
 * Explains plan row 26, "Supporting a deployment you cannot log into: preflight checks, support
 * bundles, remote diagnosis".
 *
 * This is the shape of the job when the software runs in the customer's environment. You cannot
 * shell in, you cannot read their logs, you cannot reproduce it, and the entire investigation has to
 * happen against one archive that someone else generated from a script you wrote months ago. Whether
 * that is a twenty-minute diagnosis or a week of email depends on decisions made long before the
 * failure - which collectors exist, what the redactors remove, and whether a preflight check would
 * have refused the install in the first place.
 *
 * The faults are the three ways the bundle arrives useless, and all three are your fault rather than
 * the customer's. The collector nobody wrote. The redactor that ate the evidence along with the
 * secret. And the preflight that would have caught it at install time and was skipped with a flag
 * you added for exactly this purpose.
 */
import { clamp01, stepAt, type Machine, type Scene, type SceneNode } from "./types";

const NO_COLLECTOR = "no-collector";
const OVER_REDACTED = "over-redacted";
const PREFLIGHT_SKIPPED = "preflight-skipped";

const PLACES: Array<[string, string, number, number, "actor" | "service" | "store"]> = [
  ["pre", "Preflight", 30, 44, "service"],
  ["install", "Install", 118, 44, "service"],
  ["collect", "Collectors", 210, 44, "service"],
  ["redact", "Redactors", 268, 110, "service"],
  ["bundle", "Bundle", 150, 134, "store"],
  ["you", "You", 40, 120, "actor"],
];

const EDGES = [
  { from: "pre", to: "install", dashed: true },
  { from: "install", to: "collect", dashed: true },
  { from: "collect", to: "redact", dashed: true },
  { from: "redact", to: "bundle", dashed: true },
  { from: "bundle", to: "you", dashed: true },
  { from: "you", to: "pre", dashed: true },
];

export const supportBundle: Machine = {
  id: "support-bundle",
  title: "Diagnosing an install you cannot log into",
  short: "Support bundle",
  subtitle: "One archive, generated by someone else, from a script you wrote months ago. That is the whole investigation.",
  topicIndices: [26],
  steps: ["Preflight", "Install", "It fails", "Collectors run", "Redactors scrub", "You read the bundle"],
  faults: [
    { id: PREFLIGHT_SKIPPED, label: "Installed with --force", blurb: "The check that would have refused this install was advisory, so it printed a warning at 6pm and everyone carried on." },
    { id: NO_COLLECTOR, label: "No collector for the failing component", blurb: "The bundle is 40MB of things that are working. The one log you need was never in the list." },
    { id: OVER_REDACTED, label: "The redactor ate the hostname", blurb: "A regex matched the connection string, and the connection string was the evidence. Nothing records that something was removed." },
  ],

  scene(step, phase, faults): Scene {
    const p = clamp01(phase);
    const s = stepAt(step, 6);
    const forced = faults.includes(PREFLIGHT_SKIPPED);
    const missing = faults.includes(NO_COLLECTOR);
    const scrubbed = faults.includes(OVER_REDACTED);

    const nodes = (notes: Record<string, string> = {}, downs: string[] = []): SceneNode[] =>
      PLACES.map(([id, label, x, y, kind]) => ({ id, label, x, y, kind, note: notes[id], down: downs.includes(id) }));
    const base = { edges: EDGES };

    if (s === 0) {
      if (forced) {
        return { ...base, nodes: nodes({ pre: "warn: TLS 1.0 only" }, ["pre"]),
          tokens: [{ id: "pf", from: "you", to: "pre", at: p, label: "--force", tone: "fault" }],
          caption: "The preflight found it, printed a warning, and did not stop anything.",
          detail: "A check that can be skipped will be skipped, at 6pm, by someone who has a window and a warning they do not have time to understand. The distinction between advisory and blocking is the entire value of preflight: this exact failure was detectable before a single component started, and the finding is sitting in a terminal that has since been closed. Make the checks that predict unrecoverable failures blocking, keep the list short enough that the blocking ones are credible, and put the version and the outcome of every check into the bundle so this decision is visible later.",
          fault: "A blocking condition, checked advisorily." };
      }
      return { ...base, nodes: nodes({ pre: "14 checks passed" }),
        tokens: [{ id: "pf", from: "you", to: "pre", at: p, label: "preflight", tone: "normal" }],
        caption: "Checks run against the customer's cluster before anything is installed.",
        detail: "Storage class, cluster version, egress, CPU, certificate trust. Every one of these is a support ticket that gets to not happen, and the reason preflight pays for itself is that the customer can act on it immediately - they have access and you do not." };
    }

    if (s === 1) {
      return { ...base, nodes: nodes({ install: forced ? "proceeding anyway" : "6 components" }, forced ? ["install"] : []),
        tokens: [{ id: "go", from: "pre", to: "install", at: p, label: "apply", tone: forced ? "slow" : "normal" }],
        caption: "The install proceeds. Components come up in dependency order.",
        detail: "This is the last point at which anyone has live access to what is happening. Everything after it will be reconstructed from an archive, which is why the useful question during design is not 'does this work' but 'if this fails at 3am in an environment I cannot see, what is in the bundle?'" };
    }

    if (s === 2) {
      return { ...base, nodes: nodes({ install: "ingress: CrashLoopBackOff" }, ["install"]),
        tokens: [{ id: "fail", from: "install", to: "collect", at: p, label: "failure", tone: "fault" }],
        caption: "One component will not start. The customer sees a spinner and files a ticket.",
        detail: "The ticket will say the product does not work, because from where they are standing that is the whole of what is observable. Everything that makes this diagnosable was decided months ago." };
    }

    if (s === 3) {
      if (missing) {
        return { ...base, nodes: nodes({ collect: "11 collectors, none for ingress" }, ["collect"]),
          tokens: [{ id: "col", from: "collect", to: "redact", at: p, label: "40MB of healthy logs", tone: "fault" }],
          caption: "Eleven collectors ran. None of them collect from the thing that broke.",
          detail: "The bundle is large, arrives quickly, and contains nothing about the failure - which is worse than an empty bundle because it looks like a thorough one. Collector lists are written when a component is added and are never revisited when a component is replaced, so the gap is always around the newest thing. Two habits close most of it: collect the cluster-wide events and pod descriptions for your whole namespace rather than a named list, and after every support case, add the collector you wished you had had.",
          fault: "Nothing collected from the failing component." };
      }
      return { ...base, nodes: nodes({ collect: "logs, events, describe, config" }),
        tokens: [{ id: "col", from: "collect", to: "redact", at: p, label: "raw bundle", tone: "normal" }],
        caption: "Collectors gather logs, events, resource descriptions and the rendered config.",
        detail: "Previous-container logs matter more than current ones for a crash loop - the running container has just started and knows nothing. So does the rendered configuration rather than the values file: what the customer intended and what was actually applied are different documents, and the difference is frequently the bug." };
    }

    if (s === 4) {
      if (scrubbed) {
        return { ...base, nodes: nodes({ redact: "DSN replaced entirely" }, ["redact"]),
          tokens: [{ id: "red", from: "redact", to: "bundle", at: p, label: "***REDACTED***", tone: "fault" }],
          caption: "The redactor matched the whole connection string, including the hostname.",
          detail: "Redaction is not optional - the bundle leaves the customer's network and will sit in a ticketing system - and an over-broad pattern destroys evidence silently. The line that would have shown the ingress pointing at the wrong internal host now reads ***REDACTED***, and nothing anywhere records that a redaction happened at that line rather than the line simply being absent. Redact the password and keep the host, log what each redactor matched and how many times, and test the redactors against a real bundle rather than against the examples they were written from.",
          fault: "The evidence was removed with the secret." };
      }
      return { ...base, nodes: nodes({ redact: "12 secrets, 3 tokens" }),
        tokens: [{ id: "red", from: "redact", to: "bundle", at: p, label: "scrubbed bundle", tone: "normal" }],
        caption: "Secrets, tokens and credentials are replaced. Hostnames survive.",
        detail: "The bundle is about to cross a trust boundary in the opposite direction from usual: out of the customer's environment and into yours. Getting this right is what makes a customer willing to send one at all, and a customer who will not send bundles is a customer whose problems take weeks." };
    }

    // Whatever went wrong upstream, this is where you find out what you are holding. The faults are
    // named together because the reader's job here is to work out which of them happened - that is
    // the actual skill this row is about.
    const broken = [missing ? "nothing from the component that failed" : "", scrubbed ? "the connection string redacted to nothing" : ""].filter(Boolean);
    if (broken.length) {
      return { ...base, nodes: nodes({ bundle: "40MB, unusable", you: "emailing the customer" }, ["bundle"]),
        tokens: [{ id: "read", from: "bundle", to: "you", at: p, label: "not enough", tone: "fault" }],
        caption: `The bundle arrived and you still cannot say what happened: ${broken.join(", and ")}.`,
        detail: `The next move is a round trip - ask the customer to run something, wait for their maintenance window, wait for the bundle - and each round trip is a day at best.${forced ? " The preflight result would have told you at install time, and it was advisory, so the finding exists only in a terminal that was closed hours ago." : ""} This is why the bundle contents are a product decision rather than a support one: the cost of a missing collector is not paid by whoever left it out.`,
        fault: "A round trip you should not have needed." };
    }

    return { ...base, nodes: nodes({ bundle: "ingress -> stale host", you: "root cause" }),
      tokens: [{ id: "read", from: "bundle", to: "you", at: p, label: "diagnosed", tone: "normal" }],
      caption: "The rendered config points the ingress at a host that no longer resolves.",
      detail: forced
        ? "Twenty minutes, from an archive, with no access to anything. Worth noticing that the preflight would have caught this before the install started - diagnosing it well after the fact is the second-best outcome, and the check being advisory is what cost the customer the evening."
        : "Twenty minutes, from an archive, with no access to anything. That is the entire argument for spending design time on collectors and redactors: the difference between this and a week of email is not skill at the point of diagnosis, it is what was put in the bundle." };
  },
};
