const http = require("node:http");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const readJson = (file) => JSON.parse(fs.readFileSync(path.join(root, file), "utf8"));
const text = (value) => ({ content: [{ type: "text", text: typeof value === "string" ? value : JSON.stringify(value, null, 2) }] });
const tools = [
  { name: "get_plan", description: "Read Rasul's current Senior FDE plan rows and progress fields.", inputSchema: { type: "object", properties: { query: { type: "string" }, month: { type: "number" }, track: { type: "string" } } } },
  { name: "get_learning_context", description: "Read the indexed books, repository references, and Shell Mastery lesson context.", inputSchema: { type: "object", properties: {} } },
  { name: "list_ask_reports", description: "List Markdown Ask Lumen reports saved in GitHub.", inputSchema: { type: "object", properties: { limit: { type: "number" } } } },
  { name: "read_ask_report", description: "Read one saved Ask Lumen report from GitHub by path.", inputSchema: { type: "object", required: ["path"], properties: { path: { type: "string" } } } },
  { name: "save_study_note", description: "Write a durable study note to reports/notes in GitHub. Use only when the user explicitly asks to save it.", inputSchema: { type: "object", required: ["title", "body"], properties: { title: { type: "string" }, body: { type: "string" } } } },
  { name: "semantic_search", description: "Search the wider internet semantically through Exa when EXA_API_KEY is configured, or search the Lumen GitHub repository with provider github.", inputSchema: { type: "object", required: ["query"], properties: { query: { type: "string" }, provider: { type: "string", enum: ["exa", "github"] }, limit: { type: "number" } } } },
  { name: "get_connection_map", description: "Return the precise Lumen, GitHub, Vercel, Render, and MCP connection map.", inputSchema: { type: "object", properties: {} } }
];

function repoConfig() { return { repo: process.env.GITHUB_REPO || "rasulshaikh/lumen-fde", branch: process.env.GITHUB_BRANCH || "main", token: process.env.GITHUB_TOKEN }; }
async function github(pathname, options = {}) { const { token } = repoConfig(); if (!token) throw new Error("GITHUB_TOKEN is not configured"); const response = await fetch(`https://api.github.com/repos/${repoConfig().repo}/contents/${pathname}`, { ...options, headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "lumen-mcp", ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || `GitHub request failed with ${response.status}`); return data; }
async function callTool(name, args = {}) {
  if (name === "get_plan") { const rows = readJson("data/workbook.json").Plan.slice(1); const result = rows.filter((row) => (!args.query || String(row[2]).toLowerCase().includes(String(args.query).toLowerCase())) && (!args.month || Number(row[1]) === Number(args.month)) && (!args.track || String(row[0]).toLowerCase().includes(String(args.track).toLowerCase()))).map((row) => ({ track: row[0], month: row[1], topic: row[2], depth: row[3], hours: row[13], status: row[15] })); return text(result); }
  if (name === "get_learning_context") return text({ books: readJson("data/library-context.json"), repositories: readJson("data/repository-context.json"), lesson: readJson("data/lesson-context.json") });
  if (name === "list_ask_reports") { const result = await github("reports/asks"); return text(result.slice(0, Math.min(Number(args.limit) || 20, 50)).map((item) => ({ name: item.name, path: item.path, url: item.html_url }))); }
  if (name === "read_ask_report") { if (!String(args.path).startsWith("reports/asks/")) throw new Error("Only reports/asks paths can be read"); const result = await github(String(args.path)); return text(Buffer.from(result.content, "base64").toString("utf8")); }
  if (name === "save_study_note") { const title = String(args.title).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase().slice(0, 60) || "study-note"; const stamp = new Date().toISOString().replace(/[:.]/g, "-"); const notePath = `reports/notes/${stamp}-${title}.md`; const markdown = `# ${args.title}\n\nDate: ${new Date().toISOString()}\n\n${args.body}\n`; const result = await github(notePath, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: `docs: save study note ${title}`, content: Buffer.from(markdown).toString("base64"), branch: repoConfig().branch }) }); return text({ saved: true, path: notePath, url: result.content.html_url }); }
  if (name === "semantic_search") { const provider = args.provider || (process.env.EXA_API_KEY ? "exa" : "github"); const limit = Math.min(Number(args.limit) || 5, 10); if (provider === "exa") { if (!process.env.EXA_API_KEY) throw new Error("EXA_API_KEY is not configured for semantic internet search"); const response = await fetch("https://api.exa.ai/search", { method: "POST", headers: { "x-api-key": process.env.EXA_API_KEY, "Content-Type": "application/json" }, body: JSON.stringify({ query: String(args.query), type: "neural", numResults: limit, contents: { highlights: { maxCharacters: 500 } } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Exa search failed"); return text(data.results || data); } const result = await fetch(`https://api.github.com/search/code?q=${encodeURIComponent(`${args.query} repo:${repoConfig().repo}`)}&per_page=${limit}`, { headers: { Authorization: `Bearer ${repoConfig().token}`, Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "lumen-mcp" } }); return text(await result.json()); }
  if (name === "get_connection_map") return text({ dashboard: "https://lumen-fde.vercel.app", github: "https://github.com/rasulshaikh/lumen-fde", mcp: process.env.PUBLIC_MCP_URL || "Render deployment URL after creation", durableSource: "GitHub reports/asks and reports/notes", semanticSearch: process.env.EXA_API_KEY ? "Exa neural search enabled" : "GitHub repository search enabled; add EXA_API_KEY for wider semantic web search" });
  throw new Error(`Unknown tool: ${name}`);
}

function send(response, id, result, error) { response.writeHead(200, { "Content-Type": "application/json", "Cache-Control": "no-store" }); response.end(JSON.stringify({ jsonrpc: "2.0", id, ...(error ? { error: { code: -32000, message: error } } : { result }) })); }
const server = http.createServer(async (request, response) => {
  if (request.method === "GET" && request.url === "/healthz") { response.writeHead(200, { "Content-Type": "application/json" }); return response.end(JSON.stringify({ ok: true, service: "lumen-mcp" })); }
  if (request.method !== "POST" || request.url !== "/mcp") { response.writeHead(404); return response.end("Not found"); }
  if (process.env.MCP_API_KEY && request.headers.authorization !== `Bearer ${process.env.MCP_API_KEY}`) { response.writeHead(401); return response.end("Unauthorized"); }
  let raw = ""; request.on("data", (chunk) => { raw += chunk; }); request.on("end", async () => { let body; try { body = JSON.parse(raw); } catch { return send(response, null, null, "Invalid JSON"); } if (body.method === "notifications/initialized") { response.writeHead(202); return response.end(); } if (body.method === "initialize") return send(response, body.id, { protocolVersion: "2025-03-26", capabilities: { tools: {} }, serverInfo: { name: "lumen-mcp", version: "1.0.0" } }); if (body.method === "tools/list") return send(response, body.id, { tools }); if (body.method === "tools/call") { try { return send(response, body.id, await callTool(body.params?.name, body.params?.arguments)); } catch (error) { return send(response, body.id, null, String(error.message || error)); } } return send(response, body.id, null, `Unsupported method: ${body.method}`); });
});
server.listen(Number(process.env.PORT) || 10000, "0.0.0.0", () => console.log("lumen-mcp listening"));
